
#### general settings

name: 01_IRN_DB_x2_scratch_DIV2K_block12
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [1]


#### datasets

datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /home/ices/yl/SRDict/div2k/DIV2K_train_HR # path to training HR images
    dataroot_LQ: /home/ices/yl/SRDict/div2k/DIV2K_train_LR_bicubic/X2 # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /home/ices/yl/SRDict/div2k/DIV2K_valid_HR # path to validation HR images
    dataroot_LQ: /home/ices/yl/SRDict/div2k/DIV2K_valid_LR_bicubic/X2 # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader

#### network structures

#### network
network_G:
  which_model_G:
      model_name: InvRescaleNet
      subnet_type: DBNet
  preprocess_op: PixelShuffle
  in_nc: 3
  out_nc: 3
  # block_num: [8]
  block_num: [12]
  scale: 2
  init: xavier
  # instance_norm: true
  instance_norm: false


#### path

path:
  pretrain_model_G: /home/ices/yl/SRDict/PS-IRN/experiments/block12_225000_G.pth
  strict_load: true
  resume_state: ~ 

test_LR_ref: true
#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 5e-05
  # lr_G: !!float 1e-5
  beta1: 0.9
  beta2: 0.999
  niter: 1000000
  quant_start: 0
  train_LR_ref_start: 0
  calc_jac_start: 0
  get_batch_method: repeat

  warmup_iter: -1  # no warm up
  lr_scheme: MultiStepLR
  # lr_steps: [100000, 200000, 300000, 400000]
  lr_steps: [40000, 80000, 120000, 160000, 200000, 240000, 280000, 320000, 360000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  # pixel_criterion_back: l1
  pixel_criterion_back: l2

  manual_seed: 10

  val_freq: !!float 3e3

  lambda_fit_forw: 1
  lambda_rec_back: 4
  lambda_ce_forw: 1
  lambda_Jac_G: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 50
  save_checkpoint_freq: !!float 3e3
